{% set name = "pylexique" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylexique-{{ version }}.tar.gz
  sha256: 3d7a534225f02b40b7952d9976c1548b6382257752e2a44b6a802575056a6c2e

build:
  number: 0
  entry_points:
    - pylexique=pylexique.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - pytest-runner
    - python
  run:
    - python
    - setuptools
    - dataclasses
    - pandas
    - colorama
    - tqdm
    - click >=7.1
    - joblib

test:
  imports:
    - pylexique
  commands:
    - pylexique --help
  requires:

about:
  description: |
    Pylexique is a Python wrapper around Lexique83.
    It allows to extract lexical information from more than 140 000 French words in an Object Oriented way.

    Features:

      - Extract all lexical information from a French word.
      - Get all related words to a given word.
      - Easy to use Api.
      - Easily integrate pylexique in your own projects as an imported library.
      - Can be used as a command line tool.
  home: https://github.com/SekouDiaoNlp/pylexique
  summary: Pylexique is a Python wrapper around Lexique83
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SekouDiaoNlp
