{% set name = "pylexique" %}
{% set version = "1.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylexique-{{ version }}.tar.gz
  sha256: eaaf532bf55c70b3b7f7a8827d28de058e335cc6752b388b446dc03fdb1865e2

build:
  number: 0
  entry_points:
    - pylexique=pylexique.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - pytest-runner
    - python
  run:
    - python
    - setuptools
    - dataclasses
    - pandas
    - colorama
    - tqdm
    - click >=7.1
    - joblib

test:
  imports:
    - pylexique
  commands:
    - pylexique --help
  requires:

about:
  description: |
    Pylexique is a Python wrapper around Lexique383.
    It allows to extract lexical information from more than 140 000 French words in an Object Oriented way.

    Features:

      - Extract all lexical information from a French word such as
          - orthographic and phonemics representations
          - associated lemmas
          - syllabation
          - grammatical category
          - gender and number
          - frequencies in a corpus of books and in a body of film subtitles, etc…
      - Get all related words to a given word.
      - Easy to use Api.
      - Easily integrate pylexique in your own projects as an imported library.
      - Can be used as a command line tool.
  home: https://github.com/SekouDiaoNlp/pylexique
  summary: Pylexique is a Python wrapper around Lexique383
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SekouDiaoNlp
